### PR TITLE
double and Triple actions, long-long press

### PR DESCRIPTION
**Pull request by gerhardol**
Additions:
Double long press, triple long press and triple tap
Affects most of the changed files, but until this commit where the user see a difference (except for the minor changes below).

Holding a button after long press trigger long press on invoked button after another 2_long press.
Then it is possible to map Home to long press to long press, get recent apps after3_initial down.

Multi-key actions only require secondary button at first press, then only primary is needed.

No change but clarification: Default only applies to single long-press, single click, not any other key. (how to explain double tap creates single click?)

Possibility to set press/tap timeout to system default and tap to press timeout.
If tap/press do not match, actions may be neither press nor tap.

Bug fixes:
Invoked button should have the initial down time.

Key invoked key kept down had limit on inject key rate (was several per ms in the emulator).

Up event was not sent for secondary button, only primary.

What is not done:

I have changed the order of preferences, to match the order they appear.
If added to mainline, the preference names should either be changed or stored in other storage. Should probably be renamed.

I would like to remove tap time out. Either it is a press or a tap. Now it can be both (then press is used) or neither.
Really, even long press should be system default, but unless I find a way to tweak the tapping, it is good to have.
Maybe option should be related to system default?

Custom key: I would like to use any key (especially more than available in Screen off).

---

Most changes in PhoneWindowManager.java

Excluding:
AndroidManifest.xml versionName
ActivitySelector.java (temporary change that should have been stashed)
XService.java (enabling Pro license to May 1)

### CODE REVIEW

**Comment by gerhardol** [comment]
Cancel request, use private branch

**Comment by dbergloev** [comment]
Okay, I have started looking at some of this code, but I will not have to much time before the weekend. However, about one of the changes in e6e514fa18404f33606db0ea1f7e8dc2a884fbfa, this will not work. 

The reason why this was added was to fix an issue with long press in applications. Try to make a long press back in Firefox. It will not work with that change (Firefox should display a history popup).

**Comment by gerhardol** [comment]
I cancelled this pull request, to make a new without my private changes for my private build. The changes to merge in 3.x.g, my branch 3.x.g.p has my private changes too (3 other files, one file partially changed).

Note that the latest file is to be reviewed, the history is not so interesting as there has been many refinements over time. This is funky stuff.

Edit: Long press and long-long press works fine for me, in the latest build.

**Comment by dbergloev** [comment]
Okay, I will take the weekend to look through this.

**Comment by dbergloev** [comment]
So after trying these triple events for awhile, they don't seam to create the conflicts that I was worried about. I have started implementing this into a new branch (3.3.x). If you have any thoughts on some changes, let me know. The current state of this branch has been tested a bit and seams to be working. There is however still a lot that needs to be moved over from the 3.x branch. Only some basic key code remappings are added at the moment. I am gonna work on this during the week. 

I have split the PhoneWindowManager class into smaller multiple files in a sub-directory (pwm). It was starting to become to big. The PhoneWindowManager class itself only contains the hook classes. All the rest is moved to a Mediator class and the KeyFlags and renamed KeySetup class has got their own separate files as well. 

I also did some investigation into the Samsung sources, and for some reason they have added a secondary SamsungPhoneWindowManager class. From this class they control Haptic Feedback using a custom method and Hardcoded Key Codes. At the same time they have removed the Virtual flag from policyFlags. I did find a solution by changing the [Haptic Feedback method](https://github.com/SpazeDog/xposed-additions/blob/3.3.x/src/com/spazedog/xposed/additionsgb/backend/pwm/Mediator.java#L372) used in this module. This should provide Haptic Feedback on all Samsung ROM's without forcing it.

I also came up with a way to eliminate the module from handling Keyboards and Gaming devices, as well as a better way of checking for external devices, [which can be found here](https://github.com/SpazeDog/xposed-additions/blob/3.3.x/src/com/spazedog/xposed/additionsgb/backend/pwm/Mediator.java#L266).

**Comment by gerhardol** [comment]
I have a hard time following what was merged as there has been a lot of changes in this commit. This comment is done on a canceled pull-request as well (a new in a separate branch with some changes not to be merged excluded). I have already reimplemented my changes once. Some intermediate commits are appreciated.

Can you confirm that you have used the 3.x.g branch? (can we switch the conversation to the relevant pull request?)
Do you have any description of what has been merged?

**Pull request closed without merging**
