### PR TITLE
Reimplementation of triple button pull request

### PR DESCRIPTION
**Pull request by gerhardol**
This is the third reimplementation (and fourth pull request) of my changes related to triple events for XPosed Additions module. I will not cancel the other open pull request yet, as features are missing.

Some patches have been merged from the 3.x.g branch, some were in spirit implemented but slightly different, others are not included. As some features I want is not there yet, this is a reimplementation of those features. Most of my changes was done in PhoneWindowManager.java, so they were not merged despite the merge history. This is an early merge to hopefully work on the same codebase again.

Changes so far:
- PWM only: ADT changes only: Cleanup, correct indentation, quick-fix (add final) (to simplify further changes)
- Add Long-press "Default" key timeout and tap "Default" and "Long-press" timeout (this was the only merged from 3.x.g)
- Add hidden setting allow_remap_any, to simplify testing in GENYmotion
- Only tap delay if needed: If there are no more events (double or triple), click actions can be executed immediately. This required some internal restructing 

There are a few TODO and xxx in the code.

### CODE REVIEW

**Comment by dbergloev** [comment]
I don't get your `Only tap delay if needed`. I have never used tap delay if there was no tap actions, and I still don't in 3.3.x, so what exactly is it that you are changing? 

Default press/tap delay is not going to work. The settings will display one delay (The module default) while using a different one whenever a user does not change the settings. Settings and actual behavior has to match. 

[Changing the order of configs](https://github.com/gerhardol/xposed-additions/commit/b1483800275d32f80bb8df890499dc9d140c005b#diff-7d460c504a766a5b1575789823319053R512) is not being merged. I made the special array in order to keep compatibility with older configs. I cannot have people reset their options on each release.

[Wake key handling](https://github.com/gerhardol/xposed-additions/commit/b1483800275d32f80bb8df890499dc9d140c005b#diff-7d460c504a766a5b1575789823319053R512) is moved to the mediator. 

[Yes it should](https://github.com/gerhardol/xposed-additions/commit/b1483800275d32f80bb8df890499dc9d140c005b#diff-7d460c504a766a5b1575789823319053R512)

Here is the thing. I have added was seamed important from your changes. I am not gonna change something like the whole code structure, just because you might like it better. If I am gonna merge something, you can't just through me 46 randomized commits. I need specific detailed commits that refers to an enhancement, addition or a bug fix, one per commit. 

And I am not trying to be rude. But if I understood your changes better, especially the reasons for them and if I got some more clean commits, it would be much easier to figure out whether to merge them or not. I am not just going to merge 46 commit just because someone sent them to me. And neither can I promise that I will merge them without additional changes.

**Comment by gerhardol** [comment]
Only tap delay if needed
Your code adds a delay for double and triple actions, also when no actions may follow:
    if (mEventManager.hasTapActions() && mEventManager.getTapCount() < 3) {

---

Default longpress, default/long-press tap delay:
Is in the settings too. The settings matches.
(That is actually the only commit that survived from the 3.x.g merge).

---

The order actions are stored in preferences, only the structure in EventManager, 
That simplifies the the handling for tap delay. Using one structure is simpler than one. There is no need for any special double/triple handling.

---

Wake key is not something I have looked at yet. (Cannot see why some of that is needed, that is an Xposed/Android question, nothing to do with this module.)

---

Ongoing keys:
I was mislead by the naming: mEventManager.getParentEventKey() is "get other key".
So this is handling the case one of the keys are released, the other is kept.
However, I still would like to tweak this, the secondary key should not be needed for taps.
In addition, it does not handle the case the "other" key was pressed multiple times, neither single nor multi repeats for long-press.

In my implementation, I ignored default behavior for repeats. One reason was to avoid such situations, what is the correct implementation? The other is that unless long-press and tap delays are synced, it is easy to miss presses/delay.
This is either way for me, but it need to be consistent to be a feature.

---

I am making minimal changes. The changes are there for a reason. (The ADT quick-fix/indentation was done to avoid annoying changes later.)The key handling is too dependent to have one feature, one commit. That is why I made this early pull-request, to not have to sync your changes again while updating myself. If not these changes are merged, I will spend time on making compatible changes. (The couple of xxx/TODO should be updated of course, but it is hard to find what is merged and what is not since you have done your changes in one major change.)

**Comment by dbergloev** [comment]
1. **Tap Delay**: The module has no tap delay if no action is set. Like you pointed out yourself `mEventManager.hasTapActions()` is checking for tap actions before setting a delay. If there are none, then no delay is used. 
2. **Default Timeout times**: The XServiceManager will get a default delay from `configs.xml` if no user defined timeout has been set. This is the case for all default settings in the module, and I want it to stay that way, as it provides an option to customize them and it also provides consistency on how the module handles it's settings. 
3. **Order in Preferences**: I am not making any special handing, I just want to separate clicks and presses. Your way is fine as well, so I will not get into this as this is simply two ways to do the same thing. However, I will not have tap events being registered as simply clicks. I control haptic feedback in the Mediator based on Clicks, Double Clicks and Presses, so simply parsing Click for both will not work. And it makes no sense to make an additional parameter to parse tapCount. 
4. **Wake Keys**: This was not a bad idea, they do seam to be needed. However they need to work in a specific way and even in my version, it needs to be tweaked a bit. Wake Keys should only be invoked when there is a wake flag and we are dispatching default events (Not when just parsing it do the default methods), and they should not be invoked when doing custom actions (I think mine does at the moment). 
5. **OnGoing Keys**: This was made to fix issues with some ROM's that stores key down event booleans and disables buttons until they get a key up (This is a ROM issues as they should automatically resume when a new key down happens). SlimBean is an example of a ROM that creates problems on certain events. And also, these methods are already synced from the Native Event Manager. There is no need to worry about this part, events will be handled in the same order as they are triggered. And only one event is sent at a time to each of the two methods. 
6. **Changes**: Like I said in the last comment, just because you create a change, does not mean that it will be added and if it does, it does not mean that it will be added without additional changes. I can't just except a change just because someone wants it, there has to be a reason for it. Now I am willing to go through the last commit b148380 and see if this is something that I can work with, but unless you specifically point out something in the remaining 45 commits, I am going to leave those alone. 

And yes the large commit from my part properly did not make it easy, but it had to be done. The class was getting to cluttered and it made it difficult to work with. The module has grown a lot in the last year and the file structure had to follow. However this was a one-time thing, I don't have any plans of changing this much on each release.

**Comment by gerhardol** [comment]
Of course it is up to you to include the patches you want. If you do not, I work on a fork. Not what I want, but it is not my decision, it is your project.
1. tap delay
   If you have a tap delay setup, but no triple delay, there will be an unnecessary delay when double clicking with your code.
   Similar for triple-click, will always be a delay.
2. default delay
   The setting for the drop down value"Default" means that the globally configured value is used.
   Of course you can configure any value in this module too.
3. configurations
   The handling is more than tap or not. 
   I unified the structure to make the implementation (related to 1.) minimal.
   Sure, that could be reversed.
4. wake keys
   I added a comment because that was something to investigate. The handling is deliacte...
5. ongoing
   The code comment was really triggered about: How to handle default when tap > 0?
   The ongoing is needed also for non default keys.
6. merges
   I have assumed that I needed to implement many of my changes a third time (OK, first time not everything was implemented). If you consider merging now, I will make the changes minimal but weird rather than adjusting functionality.

From what I can recall without seriously comparing implementations are the following:
- long-press also for injected keys (long-long press)
- Power key probably needs special handling when mapping
- power/wakeup tweaks (investigation)
- some locking needed (ongoing keys etc)?
- default long press depends on the user holding about 50ms extra. OK?
- default handling when taps > 0
- long-long-long press for Power (missing ROM feature, reset when pressed for 8-12s normally)
- toweak to previousApp

**Comment by dbergloev** [comment]
1. The Tap check is a general one that returns true if any tap actions exists, not just double but triple as well. But yes, after a double tap, there is no need for a second delay if there is no triple action. So if this is what you mean, then you are absolutely right.
2. Well that could be the case of cause, I can properly work that into the current configuration handling. But as it is now, default has a fixed value in configs.xml
3. I will need to look more into your changes before commenting more on this.
4. As it is with the release that I just published, wake keys are handled by the module when no action is available, but we still inject the keys. 
5. The module already handles tap > max. It simply injects the amount of taps that have been recorded. 4 taps = injects 4 down/up since we do not have 4 tap actions. 
6. I will look this over.

**Comment by gerhardol** [comment]
1. ongoing
   See 6th item in changes from 3.x.g
   Adding other comments in next update
2. features
   Added long-press also for injected keys (long-long press)

One more feature to add from 3.x.g:
- Do not handle unconfigured keys at all. (related to wakeup). I rather remove the external device check completely.

**Comment by dbergloev** [comment]
I can't remove the external device check, it created to many problems with keyboards and gamepads.

Also I think the whole EventManager needs a rewrite, from both sides. It should not be limited to a specific amount of keys. It should keep track of all keys and their current dispatched state. If a user presses a 3 button combo, it will break both any original support along with the modules current ongoing event. This is also why keyboards are creating so many problems. It would also automatically add your injected long-long press and whatever other events is support by a receiver.

**Comment by gerhardol** [comment]
Sure, EventManager could neeed a rewrite. Everything is dependent (the original Android code is not too beautiful too).
But I doubt you would be happy if I did the rewrite!

I believe just relaying unconfigured keys could replace the external device check. It is not important for me, just mentioning. (feedback was OK for those that used my build)

However, unconfigured keys brings me to a question (primary to myself): Why is not just returning having the same result as not having the module at all?

**Comment by dbergloev** [comment]
Excluding unconfigured keys is not that easy. I did this in 2.x, but that was before I added combo options. Just because `Power` is unconfigured, does not mean that `Power+Back` or `Power+Home` is not. With combo options you can't easily check if a button is unconfigured. 

And you are right. Android's code is not great. The whole structure for key control sucks.

**Comment by gerhardol** [comment]
Detecting if Power, Power+x is configured is just a datastructure.  (I implemented that for 2.x I believe, clumsy as storage was not changed). 
But that is not a prio for me, still, it was just many users asking about it at that time.

**Comment by dbergloev** [comment]
But if one could get the EventManager working properly, it should not mater. And it would be a better way since it creates consistency. 

An even better way is to just remove the Native handler by doing it's job. The reason why we inject keys, is so that they are dispatched across the processes to all of the applications. What if it was possible to do this manually without the need to parse it through the Native part? That way we do not need injection and we can dispatch the original KeyEvents object as they are with our own minor changes via reflection. It would provide the module with complete control. I have been looking at this, but there is a lot of Native code handling this. Cannot quite figure out which internal service is provided with the result from the PhoneWindowManager. My bet would be some where in the ActivityManager section.

**Comment by gerhardol** [comment]
The old 3.x.g pull-request was closed. The following would be the missing parts:
- Default handling: Inconsistent default handling, when no action mapped. The current implementation repeats clicks for primary but not for secondary and not at all for long press.  (What is the default for long-press?)
  - I rather have default handling for single only, otherwise ignore. (Button selection GUI: Default for single, disabled for multi)
  - Second alternative is one invocation only, regardless if detected on single/multiple. (GUI: Default, but describe in doc?).
  - Third is similar to now, but remember the clicks also for secondary (could differ from primary).
- "Pass-through" of unconfigured keys is not implemented (minor interest for myself, not interesting for Daniel. I believe it makes generally sense though.)
- Clean-up (even if I had to make more "common" changes than planned).
-  Double-tap detection if no double long press or triple actions (removed on request, there were questions in xda forum about it though).

Missing:
- Is till miss app shortcuts, even if the GUI is rough. There will be requests for more than Tasker, I use Llama that has no dedicated external interface, just shortcuts. The implementation in 3.3.0-b2is not on github, could it be shared?

**Comment by dbergloev** [comment]
So these commit's is what I should look at?

And I don't have the code for shortcuts any longer. It was just a test, so I never made an actual commit of it. But I will look at adding it again, but it needs a proper implementation with a custom view setup. Also it needs a group functionality that groups all shortcuts from each package into one, and then displays all in a specific package when selected.

**Comment by gerhardol** [comment]
Yes, this is what works for me, tested on 4.2 and 4.4. The only change that should be ROM dependent is long-long press (long press for buttons mapped to long press), but that should work the same way as default long press.

For shortcuts I prefer something similar to Nova where you first select shortcuts, then the app, then the condition. The current Tasker support is omitting the first step (but using a different interface).
Other open source apps that support shortcuts are Trebuchet and ADW.Launcher. None are a natural fit into XA (ADW do not list Tasker?). There are few code examples.

**Comment by gerhardol** [comment]
If you commit the latest, I can merge to that first. I suspect we have done the same changes for a few changes...

One thing more, suggesting review procedure.
As everything is dependent, the commits are not strictly feature by feature, they are updated too.

Take .xml/Settings.java and related changes in pwm first. Mostly trivial if you accept the change.

For pwm, that was not automerged when moving to 3.3.x. So almost all commits I did to the 3.x.g branch was ignored.
If you do not accept my first commit "No functional changes, ADT changes only: Cleanup, correct indentation, quick-fix (add final)", compare my latest to that commit. (otherwise make the same change yourself.) That should decrease other diffs later.

Review PhoneWindowManager first, the other when necessary. Go back to commit comments if needed. You will eventually want to change the flow. I of course appreciate if you make separate commits for the merge and changes...

**Comment by dbergloev** [comment]
Okay I have pushed the last changes.

**Comment by gerhardol** [comment]
Changes pushed (separate commit of 3.3.x in my clone for non functional "ADT" changes)
Briefly tested only.

Note: XService does not compile with the latest version

**Comment by dbergloev** [comment]
What do you mean by not compiling? These changes is what is in the currently released version and is compiling just fine on my PC. Try clearing old project caches.

**Comment by dbergloev** [comment]
B.t.w. you are using to much final. The properties are only used internal in EventManager which means that final is not needed. And the parameters are not used within any sub-instances or anything similar. 

Not the properties are fine, although not needed it does make a more clean structure to have those as final when they are not meant to change, but parameters and internal variables makes no sense at all. It's like adding multiple semicolon after each statement, it creates no errors but it makes no sense to do so.

**Comment by dbergloev** [comment]
This is the status of your most recent commits.
1. [72eb6a6](https://github.com/gerhardol/xposed-additions/commit/72eb6a674fba022a400bf499416ff0baf82fc0c6) is not getting merged. I don't get this one. Whenever a combo event is detected, the Tap Count is reset. This will never conflict. 
2. [efe4438](https://github.com/gerhardol/xposed-additions/commit/efe44382f78d2add0382effd747224f4dfb7b98d) has been manually added in [fb6c8ddd](https://github.com/SpazeDog/xposed-additions/commit/fb6c8ddd6f098b36491cc6ca68c4108e6b44718b). Everything that is non-hooked methods, should be in Mediator. 
3. [98d0c63](https://github.com/gerhardol/xposed-additions/commit/98d0c63369dc5fe75f2e5b307210b0be99ee293b) is not getting merged. `startActivity()` will never through `ReflectException` as this is an internal Exception in `ReflectTools`. If you want a `try/catch` it should instead be `Throwable`, which will catch anything. 
4. [1d1d226](https://github.com/gerhardol/xposed-additions/commit/1d1d226aef41d95d4fdacaef392267640ed2b92b) is not getting merged. `interceptKeyBeforeQueueing` and `interceptKeyBeforeDispatching` are both synced via the Native handler. This means that they can only handle one key each at a time. So if we have a up event in `interceptKeyBeforeQueueing` and a down event in `interceptKeyBeforeDispatching` and both is the same key, then there is no way that the `onGoing` status can change, as these two events needs to be processed before any new events is parsed from the Native handler. All events get's Queued, and all will be handled in the correct order one by one. Google have made sure of this, so no need for internal testing of this part. 
5. [5236e58](https://github.com/gerhardol/xposed-additions/commit/5236e58acd5114c2b41bbb8b349c0ad609c924c2) is not getting merged. This check has already been performed by the loop. If these values was changed, the timeout would never get below 0 since the loop would break before that time. Especially now where the delay has been changed to 1ms sleep time. This additional check is pointless. 
6. [6c82c6b](https://github.com/gerhardol/xposed-additions/commit/6c82c6bca622f42972c769fda65c44625695c73f) is not getting merged. A specific key's repeat count and queued information belongs to the key itself and not the event in general. This is key information and not event information. 
7. [55a7192](https://github.com/gerhardol/xposed-additions/commit/55a7192dd0626118ef7a384d927c93c185598c64) Still don't get this `SpecialKey`. 
8. [2061a1d](https://github.com/gerhardol/xposed-additions/commit/2061a1dcba9ac18e2a0ce441252f005d538a86c4) I am not going to overwrite default Haptic Feedback settings. The Haptic Feedback is already internally in Android made up of different categories such as Virtual, Long Press etc. It is up to the ROM to handle these.

**Comment by gerhardol** [comment]
Not at home, best attempt to answer.

Compiling
https://github.com/SpazeDog/xposed-additions/commit/93dd6cddbace087c358c9b0e5548f9168bd9bf4e
Probably got a runtime error, had to reverse the patch
Completely unrelated to the pull request, just a note if all was committed.

final usage
The primary intent was to use the project setup to setup the code to limit noise from changes after. So the change was "automatic". I did this in a separate commit.
Personally, I prefer setting final, then it is simple to see if a parameter is changed even if the compiler should find this too.
1. Combo count
   tap count should not be increased for both primary and secondary key down.
   Double events are using Triple event actions, triple combo are not handled at all (always null).
2. power reset
   OK
3. launchIntent
   Some users with pre SDK.MANAGER_MULTIUSER_VERSION (< 4.2?) had errors when an activity could not be started from system (that was in my build, due to mishandling in that, but there were similar errors in 3.2.2).
   The change should catch in pre SDK.MANAGER_MULTIUSER_VERSION as in latest releases.
   My merge with your code was incorrect, I missed that it caught on ReflectException.
   Could just catch on anything for all versions in my opinion, does not matter for me.
4. check ONGOING for click events
   OK. These predefines are extremely hard to know, what ROM follow and what not.
   I had an error here, both click and long-press executed, but that was together with another piece of code.
   I suggest the check in the while loop and within synchronized() is always using eventTime, making sure registerKey() has a unique time stamp (or timestamp plus a counter) to minimize the checks required.
   Note that the while loop for ongoing keys (INVOKED) cannot use the same checks as the ONGOING, the key handled is not the latest handled for secondary and non-default long-press.
5. check conditions after a loop
   Similar to above, the check in synchronized() should be consistent.
   (in your code the interceptKeyBeforeQueueing could insert the up key, then the down key is inserted in interceptKeyBeforeDispatching, so there is a risk).
   I am OK with the change. However, I prefer the check in synchronized: For injected long-press, any event could interrupt the timer when it reaches 0 (even if low probability), then I believe it is slightly more correct to discard the repeated key.
6. last key queued
   lastQueued key is a EventManager property in my opinion, it is was the module handled. I could not use the EventKey to check parent keys in long-press check. (The check was never committed, not needed and too long).

repeat count was not used (other than for printouts), I do not think it was updated properly.
1. specialKey
   SpecialKey was a way to handle the GlobalActionTimeout. I later found out how to handle this correctly, so this was reworked in next commit.
   Everything is so dependent, it is hard to keep all separated.
   (This is why I suggested reviewing the full committ rather than the individual committs).
2. long-press feedback
   Feedback is of great help to handle long-press vs long-long press. It is not always possible (or desired) to have haptic feedback for all keys.
   In search of a better solution, I added this as a non-gui configuration. Can you please keep this?

**Comment by dbergloev** [comment]
Yes I think that you are right, I need to look at your files in complete forms instead of separate commits to gain a better overview. 

But right now I have some fixes that needs to be pushed to public release, one of which is some power control that creates certain issues on some devices. This needs to be done before I start playing with integration of larger parts of your changes, so to begin with, is there something smaller that I should add to the next release? The Long Press Feedback could be one of them, don't think that will take to long or require to much testing. 

Also you might find [this](https://github.com/SpazeDog/xposed-additions/commit/72d3079bf860314d33f7bca97269bd7d872402d7) commit interesting. To few Play Store Torch apps support Intents, so I thought it was about time to play with Native support instead.

**Comment by gerhardol** [comment]
Of course, you decide what to include in releases...

Consider including 1. (tap count for combi events). I believe it is just a simple bug.
Maybe catch exception in startIntent, to remove that from the list.

The rest is mostly related to long-long press (long press from buttons mapped to long press), so I suggest waiting. The extra haptic feedback is primary of interest there so no need to merge otherwise.
Note: This increases the usability for non-Pro users with 50%, should this be Pro?
(I can for instance map Home key to Back/Home/Recents, see my mod thread (link on page 131) for details.)

Some of the "disputes" we have (for instance to while/synchronized checks) occurs due to I did not write better checks to keep the diff down. The latest commit at least has comments in some situations where I believe the code should be changed. But I have no better suggestion how to handle this. Sure, I could provide suggestions i pull requests, but even git has a problem handling all branches.

If you commit, I will merge again (I am not home so much now, may take time). In that case, do you want the 'final' to be reversed then?
(It will be a pain to back, if you merge manually, there is not much point.)

Torch: There has been discussions, so something should be done. I would prefer using app shortcuts instead, but then there is the non-Pro users. I do not mind this change though, reasonable implementation.

**Comment by dbergloev** [comment]
The `tap count for combi events` I still don't get. I have tried all kinds of events, `Double Click`, `Touble Long Press` and the same with Triple, all using combo and I have had no issues with it.

The `final` I can live without. If they should stay, it should be throughout all class files, but I don't use it unless it is needed for some reason. 

Shortcuts is on the ToDo. I am gonna look into those once I get these fixes released.

**Comment by gerhardol** [comment]
This increases tapcount for both primary, then secondary for double/triple events.
If it works for you, then you use only one of the keys the second time.

public Boolean registerKey(Integer keyCode, Boolean isKeyDown, Integer policyFlags) {
...
                if (mState == State.ONGOING && (keyCode.equals(mPrimaryKey.mKeyCode) || keyCode.equals(mSecondaryKey.mKeyCode))) {
                    mTapCount += 1;

```
                if (keyCode.equals(mSecondaryKey.mKeyCode)) {
                    mSecondaryKey.mIsKeyDown = true;

                } else {
                    mPrimaryKey.mIsKeyDown = true;
                }
```

**Comment by dbergloev** [comment]
Sorry but second time? The way you handle combo keys is just like handling only one key. The difference is that you keep another key pressed down while doing your clicks, taps, presses using a secondary key. 

At the moment there are only one issue that needs to be fixed with combo and that is that the event should not end until both keys is released. This means that if you press Power and then double click with Back, you should be able to keep double clicking with back and execute the same action over an over until you release both Back and Power. 

But if there is another issue, then I need a little more specifics, cause I am not quite sure what you mean?

**Comment by dbergloev** [comment]
https://github.com/SpazeDog/xposed-additions/commit/47aecb230805f7eb37c72e30b4c774bd2d605bd1

I think the above commit fixes whatever issue you where talking about, and at the same time it fixes what I was talking about. As long as the primary is kept down, we have a combo event. 

The only issue is using the Power button as primary since most device kernels has been set to reboot the device after 8 seconds. But since this is a kernel thing, there is not much to do about it.

**Comment by gerhardol** [comment]
I have always used combos with the complete sequence or only repeating primary key.
Before 3.3 I believe using the complete sequence worked too.

The intention of the commit 47aecb2 should be to allow complete combi and repeating with secondary only I believe. Fine by be, I have to change my usage just (not  repeating primary only).
Too tired to think of all pitfalls, too many differences to merge this right now. It's summer.
Power with 8-12s: Should not be an issue.

**Comment by dbergloev** [comment]
Just as a notice, I am currently working on a more dynamic EventManager that is not constraint to handling only two keys at a time. Once this is done, it should be possible for better keyboard support in the future, once we get past the damn long press timeout issue that is needed to get combo's to work.

However, working on this I located the problem with some default combo events such as Screenshot. The problem is that the module now uses an event time that is set at the beginning of the event. 

https://github.com/CyanogenMod/android_frameworks_base/blob/cm-11.0/policy/src/com/android/internal/policy/impl/PhoneWindowManager.java#L920

As you can see in the above link on line 920 and 921, it compares the event time which in our case is to low because we inject the keys. So the module needs to use a fresh time on each injection to avoid this issue, just like it did in version 3.1.0 and above until this behavior was changed and broke the default combo.

**Comment by gerhardol** [comment]
Commited suggested changes to the Power reset and combi key presses.

Setting eventTime has to be done then. I would have to preferred the original time, in the case time is used (like stop timer).

**Comment by dbergloev** [comment]
I have tried using the times from the original KeyEvent object, but that is still not working, not sure why since I doubt that there is 150ms between two key events. Using current time during injection works however. 

Check out the new 3.4.x branch. And don't mind the part where I split Mediator into two separate classes. The content of both are the exact same, I just split the config part from the tools part for better overview.

**Comment by gerhardol** [comment]
Took a brief look at 3.4.x: The 3.4 branch seem to be aligning to my changes.
Do you want a new pull request for 3.4?

Please comment on the commits for Power-press and combi event commit as well (if rejected, they will not be included in 3.4).
(Mediator is not problem splitting, I have few changes there.)

The majority about the remaining changes is about long-long press: Long-press for buttons mapped to long-press.

I am not developing as it is now - just merging and preparing for pull-requests. It is not fun, more rewarding to make changes I want with minimal merges. As pull requests takes time for you, should I cancel the pull request?

**Comment by dbergloev** [comment]
The dynamic key control in 3.4 and the altered Flag handling seams to have fixed a lot of problems, at least on 2 of my test devices running GB and JB, so I think this structure will work and we can stick to it. So yes I think we should just start clean here, which means that if you can submit new changes in a nice structured way (much like your last ones), that would be great. Then we can take those one at a time.

About the two commits you mentioned, https://github.com/gerhardol/xposed-additions/commit/322cfa667c838f9fe7f21cd115727bef927d890b and https://github.com/gerhardol/xposed-additions/commit/43876c12d4a1908fb58b1c5a8fd4fe4cda76419d, I think those look fine. Especially the Long Press Power commit. Mine works, but it really needs to be fine tuned a bit. So if you make those changes so that they work with 3.4.x, I can merge those. Or I can add it manually from the current commits, that is up to you.

**Comment by gerhardol** [comment]
OK, then I will submit 3.4 patches, likely in a couple of days. Really just Power reset that can be separated I believe, most other changes are dependent.

Will propose a change to events in this pull request for review first (as it is a dead end anyway).
Will close this 3.3 request when all is in the 3.4 request.

**Comment by dbergloev** [comment]
I managed to borrow a bluetooth keyboard to do some testing, mostly to make sure that the new toggles in SpazeDog@30c000fb was working. 

One of the problems with the keyboards is the way Android handles normal letter keys like A, B, C. If you press `A` and keep it pressed while pressing `B`, then Android will do an automatic key up event on `A` before sending the key down event on `B` (even though `A` is still pressed). This will happen in Nano Seconds, which means that before `A` key up can get from `interceptKeyBeforeQueueing` to `interceptKeyBeforeDispatching` to be processed for a click event, `B` will start a new event in `interceptKeyBeforeQueueing` which will delete `A` from the EventManager and make `interceptKeyBeforeDispatching` cancel the `A` event. So if you do this in a text editor, the module will only print `B` instead of `AB`.

The second issue is that `Shift`, `Ctrl` and so on are defined in the original KeyEvent. But since we inject new KeyEvent objects, those status's is never parsed along. 

So to get full Keyboard support, these two issues needs to be sorted out. 
1. Make sure that `A` key up is processes in `interceptKeyBeforeDispatching` before `B` is configured in `interceptKeyBeforeQueueing`. I am thinking `Handler` + `Synchronization`. 
2. Make sure that the KeyEvents that we parse contains all needed information about `Shift`, `Ctrl`, `Meta` etc... Parsing original KeyEvent does not work, it breaks on some ROM's. So we need to copy this from the original object to the new one.

**Comment by dbergloev** [comment]
This commit SpazeDog@82ac5209 fixes the first issue. Since this is a cheated way of doing it, it will only be considered a temp. work-around. But while working out these issues, it will still add Keyboard support to XA.

**Comment by dbergloev** [comment]
And this commit SpazeDog@3a728dc8 fixes the second issue which adds full Keyboard support.

**Comment by gerhardol** [comment]
The updated EventManager looks fine (long-long press is an issue, but that is my problem)

Note that MediaTek devices sets InputDevice.SOURCE_DPAD (and InputDevice.SOURCE_KEYBOARD). My ALLOW_REMAP_ALL is not needed for MediaTek and GENYmotion, but default config is not working. There will be questions.

First set of patches for 3.4 submitted.

**Comment by gerhardol** [comment]
Reimplemented this for 3.4 (long-long-press not pushed yet, to be done soon)
No need to keep this open
The implementation for 3.4 was mostly cleaner than for 3.3, due to changes in 3.4.x.

**Pull request closed without merging**
