### PR TITLE
3.4.x.timeout remap

### PR DESCRIPTION
**Pull request by gerhardol**
I have a need to get a longer tap timeout than 200 ms.
Patch that increases max if the used value is close to it, see commit comments.

Also got some logcats, found a patch on the source page for SeekBarPreference.

### CODE REVIEW

**Comment by gerhardol** [comment]
Also included in the long-long-press commit

**Comment by dbergloev** [comment]
I think it would be easier to just raise the default values. I have no problems setting Max or/and minimum to something else, but doing it like this and users will start posting it as an error. They are not going to understand this as a feature, they will just see that sometimes they can set higher values than other times and think that XA has a bug.

**Comment by gerhardol** [comment]
I thought about changing the max values too (it is obviously a much easier change). I did it this way for the following reasons:
- Change appearance as little as possible
- Dont know what maximum should be. I use 300/300 myself, maybe increasing 200 to 700/400 is a good max?
- The precision is lower if max is raised

But maybe I was overworking it:
- 3.4 has not been out long
- There has been complaints to lower, but not raise timeouts, my usage is new
- Precision is not very important, even on a small screen, and not an issue on any current phone?

I suggest the first commit is kept, due to printouts. (Should pretty print though.)

Should I revert the second part and change the hardcoded max instead?

**Comment by dbergloev** [comment]
I think for the time being that the Max should just be changed. I did have plans to rewrite the entire UI and stop using Android's Preferences, but instead create a more custom interface. Maybe when I get around to this (when most current issues are resolved), we can find a better way that can be implemented into the new UI. Maybe something similar to your first suggestion about using default and custom values and such. But that is to much UI work for now if the entire UI is going to be rewritten anyway.

**Comment by gerhardol** [comment]
Notethat #19 no longer requires that combos are executed before the timeout for the first press, so the urgency is decreased. However, I still believe it makes sense.

**Comment by gerhardol** [comment]
Too late to merge this now, I will not support a merge

**Pull request closed without merging**
