### PR TITLE
2.x

### PR DESCRIPTION
**Pull request by gerhardol**
key remapping rewrite. 
A lot has been changed in PhoneWindowManager.java
Note that Common.java will need manual adaptions

Added action SwitchToPrevious app.

Consistent handling of actions:
- Longpress is detected if keys are pressed for the longpress timeout, cancelled if any key is up.
- Click is detected if not longpress and no other keys pressed.
- Double tap detected if keys are pressed twice in sequence. The action is executed when the keys are down (this is different from click).  

This adds the possibility to get Longpress detection also for mapped actions. Previously all key codes were mapped to single clicks. The up key event is sent at next up event. If there are no more up events, it is sent immediately.
This means that Single key Click always have immediate up. All other events can get both single click and longpress.

An example, using actions using Menu key where click is mapped to Settings and longpress to Search.

If for example Vol+ is set to Menu, Click will always result in a single click on Menu. Longpress on Vol+ will give Menu with normal Longpress, Search if Vol+ is down for Lonpress*2.
Double tap holding the key at second down will result in a Longpress.

With multi-key setup, for example Vol+-Home, click action is executed if one of the keys is up before longpress timeout. As the Menu up is relayed to the system at the second up, both actions are possible. Similarly can multi long press and double tap give click/longpress.

In general, the key handling is restructured to be more "protocol" handled. Implementation as previously partly in BeforeQueing partly in BeforeDispatching, now only in BeforeQueueing. 
There 

License handling is now removed from PhoneWindowManager.java, only in Common.java

Major restructuring for key detection and replace.

The default action when adding a new key for double-tap is now default, which means that double click is not monitored. Default for Click/Longpress is to relay the action to other receivers.

Increased double tap timeout

Not done:
Gingerbread testing - to be dropped?

### CODE REVIEW

**Comment by dbergloev** [comment]
Well you have been doing some work. Sorry it took me 2 month to see, might have been useful before I was done rebuilding version 3. 

I have not looked at the codes yet, but I do have a reply for some of this. The way I made the key action control was for a reason, and I know that it look kind of messy. 
1. First of all, Gingerbread did not make it easy as it's dispatching method is missing one key element, the ability to send timeout/retry events to the native handler. In Android above Gingerbread, you can return positive integer representing a delay in milliseconds, which will force the native handler to do a timeout and then recall the dispatcher before dispatching the key to the entire system.
2. Long Press also has some problems that needs to be handled. First of all, if regular applications receives a key with a positive repeat flag without first getting a 0 repeat key down, they will not execute long press actions. And I don't want anything to get anything before it has been decided how an event should be handled. Some applications could have some action for a key down event, and if that key code has been re-mapped to another, the application should not get the original. For an example, if we remap key 84 to act as 82 and an application contains a key down event on 84, we would create problems if we dispatch the key down event of 84 before we have changed it to 82. 

I will have a look at your code. I am kind of interested in how your solutions work. In the mean time, you could check out the new PhoneWindowManager in version 3.x once I upload it. There is a bit more consistency than in 2.x as it handles all keys and not just the active once.

**Comment by gerhardol** [comment]
Hello

I have done a lot more since the pull request, it is more interesting to
look at that I believe.
I am not completely ready yet, has some longpress to add.
My last weeks have been very busy.

The latest code (not pull request) should handle the key mapping problem
you describe.
However, Gingerbread support is dropped in my updates. It should be very
few devices that run XPosed that are not on custom ROMs anyway. You should
have statistics.

The code base was good in my opinion, but still I needed to a rewrite to
understand it.

A word of advice: You should respond in the forum to state that the module
is not dead, before your business is gone.

My intended use is for an Omate TrueSmart, a full Android phone in a watch
format. The device have two buttons, but you need more to handle it - a wet
touch screen is of no use.

/Gerhard

**Comment by dbergloev** [comment]
I have already written on XDA and posted a beta of 3.x :)

Gingerbread support is still needed in my release, since there are several users (More than one would think), most of them using custom GB ROM's because of bad driver support for camera and such on hacky unofficial ICS and JB ROM's. also, it took to much time cracking the solutions to get it working on GB with it's limited options, so I think that I will make use of this a while longer. My new class is much less cracky than the one in 2.x with much better solutions. 

I like the way you got long press working on key injection. But will that not create to much of a delay when the user releases the button and until the action is actually invoked? That was my concern and reason for dropping that idea. 

About Omate TrueSmart, what you want is to intercept key events on your SmartPhone?  

## B.T.W

I found a bug in the some KitKat ROM's. The PolicyFlags that is parsed to the Dispatch Method in PhoneWindowManager will always have KEY_INJECTED even regular key presses. Those in the Queueing method are correct though. This will break your long press event. My solution was to hook InputManager and add the flag to the KeyEvent object and check KeyEvent#getFlags instead of the PolicyFlags in the Dispatch method. 

``` java
public class InputManager {
    public static final String TAG = InputManager.class.getName();

    protected int FLAG_INJECTED;

    public static void init() {
        if(Common.DEBUG) Log.d(TAG, "Adding Input Manager Hook");

        if (android.os.Build.VERSION.SDK_INT >= 16) {
            InputManager hook = new InputManager();
            ReflectClass service = ReflectTools.getReflectClass("com.android.server.input.InputManagerService");

            service.inject(hook.hook_constructor);
            service.inject("injectInputEvent", hook.hook_injectInputEvent);
        }
    }

    protected XC_MethodHook hook_constructor = new XC_MethodHook() {
        @Override
        protected final void afterHookedMethod(final MethodHookParam param) {
            FLAG_INJECTED = (Integer) ReflectTools.getReflectClass("android.view.WindowManagerPolicy").getField("FLAG_INJECTED").get();
        }
    };

    protected XC_MethodHook hook_injectInputEvent = new XC_MethodHook() {
        @Override
        protected final void beforeHookedMethod(final MethodHookParam param) {
            if (param.args[0] instanceof KeyEvent) {
                if ((((KeyEvent) param.args[0]).getFlags() & FLAG_INJECTED) == 0) {
                    if(Common.DEBUG) Log.d(TAG, "Adding FLAG_INJECTED flag on KeyEvent " + ((KeyEvent) param.args[0]).getKeyCode());

                    /*
                     * KitKat has an error where PolicyFlags[FLAG_INJECTED] will always show the key as injected in PhoneWindowManager#interceptKeyBeforeDispatching. 
                     * Since our PhoneWindowManager hook depends on being able to distinguish between button presses 
                     * and actual injected keys, we have added this small hook that will add the FLAG_INJECTED flag directly to the
                     * KeyEvent itself whenever it get's parsed though this service method.
                     */
                    ReflectTools.getReflectClass(param.args[0]).getField("mFlags").set(param.args[0], ((KeyEvent) param.args[0]).getFlags() | FLAG_INJECTED);

                } else {
                    if(Common.DEBUG) Log.d(TAG, "The KeyEvent " + ((KeyEvent) param.args[0]).getKeyCode() + " already contains the FLAG_INJECTED flag");
                }
            }
        }
    };
}
```

**Comment by gerhardol** [comment]
Preparing request for 3.x, no need for 2.x

**Comment by gerhardol** [comment]
Hello
I have reimplemented my "triple actions" in 3.x. There may be some tweaks
over time and some open issues listed below.
You can find the update on GitHub. I will make a pull request when you
believe it is Ok, but I would appreciate if you could give an indication.
It is not so much changes this time compared to 2.x. Still, I would
appreciate a pull, merges have been conflicting and I do not want to
maintain a beta forever.

Details below, more in commit comments.

/Gerhard

Additions:

Double long press, triple long press and triple tap
The GUI is in the latest commit: b15574c42e67a4152d2c14c78378fbbd4b9918fc
Affects most of the changed files, but until this commit where the user see
a difference (except for the minor changes below).

Holding a button after long press trigger long press on invoked button
after another 3_long press.
Then it is possible to map Home to long press to long press, get recent
apps after 4_initial down.

Multi-key actions only require secondary button at first press, then only
primary is needed.

No change but clarification: Default only applies to long-press, single
click, not any other key. (how to explain double tap creates single click?)

Bug fixess:

Invoked button should have the initial down time.

Key invoked key kept down had limit on inject key rate (was several per ms
in the emulator).

Up event was not sent for secondary button, only primary.

A null check in ActivityMain

What is not done:

I have changed the order of preferences, to match the order they appear.
If added to mainline, the preference names should either be changed or
stored in other storage. Should probably be renamed.

I would like to remove tap time out. Either it is a press or a tap. Now it
can be both (then press is used) or neither.
Really, even long press should be system default, but unless I find a way
to tweak the tapping, it is good to have.
Maybe option should be related to system default?

Custom key: I would like to use any key (especially more than available in
Screen off).
Enter key code manually.

Some TODO added where I am unsure of the functionality

Sure there is more.

What you do not want to pull:
XService.java
Unlocked to May 1. This is how I would like to release test builds.

Test

Tested mostly in GenyMotion, 4.4.2
Used live on smart watch with 4.2.2
No known changes that affects i.e. Gingerbread

Plan

Unless you merge quickly, I would like to release a time limited beta.
I can post in "your" thread or just keep it in "my" smart watch forum (also
on xda).

**Comment by dbergloev** [comment]
I am going to need some time, not only to look at the code changes, but also test this on some of the devices that I have. 

Also some more info would be nice. You main goal is to make this work with SmartWatches? What does that have to do with adding more tab and press combo's?

An addition triple tab option and maybe an additional long press by holding after first tab. But 3 different long press? Is that not a bit overkill?

**Comment by gerhardol** [comment]
I want to use the smart watch as a fitness device: GPS, HR using BT etc
The device is IP67. I guess Xperia and Samsung Galaxsy S5 may be used
similarily
This watch is using quite standard Android, but only have two buttons:
Home, Power
It uses side sweeps for Back, Menu too.
For changing the volume you need to open an app.

However, a fitness device cannot be controlled with touch screen only. A
wet screen and gloves are examples of conditions where buttons are required.
The app I use allows remapping of buttons to functions. Some required are
start/stop, lap and lock touchscreen but also start GPS, voice feedback,
switch screen are other examples of button actions.
This app (IpBike) also recognizes long press and double click.

Example setup:
  Power:
     press1 Power
     click1 Camera
     press2 Mute
     click2 VolUp
     press3 Launch app
     click 3 media next

  Home:
     press1 Home
     click1 Back
     press2 Menu
     click2 Vol down
     press3 Launch IpBike
     click3 Media Prev

Multi mostly app

I would like to use App Shortcuts as used in Launchers too. Then I can use
Llama events as targets to set events, like "GPS on, set screen timeout,
set fixed brightness, wifi off, sync time, start IpBike". Similar for
"wrist".

Multi key actions are a little difficult to do when moving. Single key
actions are slightly easier.

The changes are mostly restructuring, a general approach instead of
hardcoding.
So I do not know what detail you need.
For instance, injectInputEvent() has parameters instead of making
assumptions from "repeat"
I have tried to make minimal changes, would like to have changed more...

If you think it is "too much" to have triple actions, the visibility can be
hidden from normal users by having a (general) preference.

/Gerhard

**Comment by dbergloev** [comment]
App Shortcuts is already on the todo, and it would properly have been added already, had Google written some documentations about it. But there is not much to find on their developer section, so I will have to figure that one out based on their source codes instead. 

Like I said, I will look at the changes and also run some test. It would properly not be such a bad idea to have additional features added to each button.

**Comment by gerhardol** [comment]
Note: Latest update in my kit skips not tracked keys.
You said something on the maillist that you had to add a delay.
In reality, the difference is minimal in applications though. For click the
application do not react until key goes up anyway, so the delay is not
visible.
(I wanted to change the handling of default keys first, but skip that for
now)

/Gerhard

**Comment by gerhardol** [comment]
I have updated on GitHub again and plan to submit a pull request shortly.
There was problem with keys mapped to longpress actions, that cannot be
dispatched without setting longpress by default. But the current solution
works.
The Power button is a little fickly to map as well, but nothing really
changed there I believe.

I also plan to release a beta, with time limited Pro functions.
Do you want me to keep that outside the xda thread?
I have no plans of forking.

/Gerhard

**Comment by gerhardol** [comment]
Pull request sent.

Any comments on me releasing a beta?
I would like to add custom keys too, see if I get to fix that.

/Gerhard

**Comment by gerhardol** [comment]
Hello

I resubmitted the pull request, using a branch without files that should
not be merged (cherry picking from my dev branch).

I would recommend a visit to the forum again.
I believe I have solved some of the issues often raised there too.

/Gerhard

**Pull request closed without merging**
