### PR TITLE
Double long press, triple long press and triple tap, long-long press

### PR DESCRIPTION
**Pull request by gerhardol**
Additions:
Double long press, triple long press and triple tap
Affects most of the changed files, but until this commit where the user see a difference (except for the minor changes below).

Holding a button after long press trigger long press on invoked button after another 2_long press.
Then it is possible to map Home to long press to long press, get recent apps after3_initial down.

Multi-key actions only require secondary button at first press, then only primary is needed.

No change but clarification: Default only applies to single long-press, single click, not any other key. (how to explain double tap creates single click?)

Possibility to set press/tap timeout to system default and tap to press timeout.
If tap/press do not match, actions may be neither press nor tap.

Bug fixes:
Invoked button should have the initial down time.

Key invoked key kept down had limit on inject key rate (was several per ms in the emulator).

Up event was not sent for secondary button, only primary.

What is not done:

I have changed the order of preferences, to match the order they appear.
If added to mainline, the preference names should either be changed or stored in other storage. Should probably be renamed.

I would like to remove tap time out. Either it is a press or a tap. Now it can be both (then press is used) or neither.
Really, even long press should be system default, but unless I find a way to tweak the tapping, it is good to have.
Maybe option should be related to system default?

Custom key: I would like to use any key (especially more than available in Screen off).

Most changes in PhoneWindowManager.java

Excluding some files from private build in branch 3.x.g.p

### CODE REVIEW

**Comment by dbergloev** [comment]
I guessing that this is where you want the comments? 

I have not made any explicit merges from your commits. You have a lot of them, many of which I don't quite get. Also like I mentioned in the other comment, I have moved things a bit around, so the commit's would not be easy to merge when they apply to a file no longer available.

What I did was make a diff check between yours and mine and then worked from that. And although I decided to make things a bit differently than you, the features are still there. Single Click, Double Click, Triple Click, Long Press, Double Long Press and Triple Long Press. And other minor fixes like preserving flags across injection, using initial down time, moving action preparation into the KeySetup class and such. 

Now the code itself, is pretty much the same as before. The two init methods in PhoneWindowManager has changed a bit, but the Quering and Dispatching methods still work much the same. And the Mediator file contains most of what used to be in PhoneWindowManager (Although still missing a few things that I have not moved over yet).

**Comment by dbergloev** [comment]
I have looked some more at your code (And implemented a bit more, one thing at a time). However I did notice something, and I also installed your release to confirm. You have misunderstood the long press delay part a bit. It is not just a timeout for long press, but also for combo events. That is why I never added any checks to see if the user had assigned long press. 

Try adding a combo option like Volume+Back. Your action will be executed, but so will the volume trigger. Some events, like volume up and down, starts their events on key down and not key up. It's those events that makes this so difficult. 

Now I do think that these types of events are created wrong. Volume for an example should trigger one volume step on key up, but wait for the long press flag or repeat=1 before doing anything on key down. But that does not change the fact that these events exists and that I need to take those into consideration. Especially since I got a lot of complaints when I did what you have done. 

Other than that, you do have a lot of great ideas in this. For one I like the way you reduced repeating. It also slows down the volume indicator.

**Comment by gerhardol** [comment]
Thanks for the feedback. Will see what I missed (it works for me with Power-Home at least). I hardly use multi-key.  

The long-press check is always executed for the first down, then it may execute directly, so double tap works as before.

**Comment by dbergloev** [comment]
B.t.w. I don't really see the point in wasting resources on this type of check. Unless the user keep the button pressed, the timeout will never run out. As soon as a user releases the key, the flags change and it breaks the delay loop. If there really is something to notice by this, then changing sleep(10) to sleep(1) should be enough. It will then compare the flags 10 times faster, but still allow the module to detect combo's without triggering the first key down.

**Comment by gerhardol** [comment]
The check for long-press actions was added just to get the same functionality as in your code, I want to remove it too.
If number of repeats is >1, then no default is executed.
However, there were previously some problems with the checks for executed that could cause default button actions too.
Are you looking at the latest source version?
My understanding was that the latest version I push to 3.x.g would be visible in the pull request.

/Gerhard

**Comment by gerhardol** [comment]
Some changes merged in 3.3.x. Most other changes are handled in the reimplementation for the 3.3.x pull request now, even if less tested and the patches are for the unstable version 3.3.0-pre only (what is public).
Not much reason keeping this request open.

**Comment by dbergloev** [comment]
3.3.0-pre is pretty much the newest. The release version just has a few temp changes to fix some issues, but those changes is not important if I was to add most of your EventHandler changes anyways. So until that has been looked at and possibly adapted into, there is no need to push anything just yet.

**Pull request closed without merging**
