### PR TITLE
Long-long press for mapped buttons

### PR DESCRIPTION
**Pull request by gerhardol**
Reimplementation of long-long press (long press for buttons mapped to long press).
There has been several pull requests already, some has been merged (or the same conclusions done), so the difference is smaller over time.

Note commit: 
    5a080d2: https://github.com/gerhardol/xposed-additions/commit/5a080d288a383bdf17807e3265bf79a66f25d99d
Seem to be an issue for non-Pro also in 3.4.0

This first part has few actual, changes, but is preparing for other changes.
If they are not accepted, it may be possible to complete the patch anyway.

Changes so far:
- Long power press handling (discussed in the 3.3 pull request)
-      5a080d2 (Non-Pro action handling in 3.4)

### CODE REVIEW

**Comment by gerhardol** [comment]
All planned patches included. It is cb20c39 that contains the major changes
Also including pull request #15 
c499b17,    9b07281 contains functionality (minor) changes too.

**Comment by dbergloev** [comment]
Currently I am helping someone build a new kitchen, but I will look this over once I get back home. Are we talking the whole list of commit above?

**Comment by gerhardol** [comment]
All commits are included.  The last (cb20c39) is really the important one, the others are mostly building up to it. 
Vacation myself.

**Comment by gerhardol** [comment]
Any updates on the possibility of merging?
If not merged, I will extend my private build without a license.

**Comment by gerhardol** [comment]
Note: I have done a bunch of changes since this pull request that should be considered.
Not a pull request yet.

A quick review of the 3.4.x.g.p.2 indicates that the following files should be reviewed before inclusion:
settings.xml 
ActivityMain.java
ActivityViewerLog.java
XServiceManager.java

I will await a few responses before updating the pull request though

**Comment by gerhardol** [comment]
The functionality changes are included in #19 . As that implementation is cleaner and likely less corner case bugs, I will close this request, not maintain this branch. (Could have pushed the changes to this branch, but feel that the changes are big enough for a separate pull request.)

**Pull request closed without merging**
